=== atlarge-research/jsspp-osp/schemas/workload.schema.json
{
    "$id": "https://raw.githubusercontent.com/atlarge-research/jsspp-osp/v1/schemas/workload.schema.json",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Workload Description",
    "description": "A description of a workload trace for a cloud computing environment",
    "type": "object",
    "required": [],
    "properties": {
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "date_start": {
            "type": "string",
            "format": "date-time"
        },
        "date_end": {
            "type": "string",
            "format": "date-time"
        },
        "description": {
            "type": "string"
        },
        "domain": {
            "type": "string"
        },
        "name": {
            "type": "string",
            "description": "The name of the workload"
        },
        "schema_version": {
            "type": "string"
        },
        "workflows": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/workflow"
            }
        }
    },
    "definitions": {
        "data_transfer": {
            "type": "object",
            "required": [],
            "properties": {
                "source": {
                    "type": "number"
                },
                "transfer_time": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "size_unit": {
                    "type": "string"
                },
                "events": {
                    "type": "object",
                    "required": [],
                    "properties": {}
                },
                "ts_submit": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "size": {
                    "type": "number"
                }
            }
        },
        "resource_usage": {
            "required": [],
            "type": "object",
            "properties": {
                "ncpu": {
                    "type": "number"
                },
                "events": {
                    "type": "object",
                    "required": [],
                    "properties": {}
                },
                "proc_model": {
                    "type": "string"
                },
                "time_assigned": {
                    "type": "string"
                },
                "time_released": {
                    "type": "string"
                },
                "bandwidth": {
                    "type": "number"
                },
                "network": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "disk_space": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "required": [],
                    "properties": {
                        "cpu_vendor": {
                            "type": "string"
                        },
                        "architecture": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "task": {
            "type": "object",
            "required": [],
            "properties": {
                "submission_site": {
                    "type": "number"
                },
                "group_id": {
                    "type": "number"
                },
                "user_id": {
                    "type": "number"
                },
                "data_transfers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data_transfer"
                    }
                },
                "resources_used": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resource_usage"
                    }
                },
                "ts_submit": {
                    "type": "string"
                },
                "enables": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wait_time": {
                    "type": "number"
                },
                "workflow_id": {
                    "type": "string"
                },
                "events": {
                    "type": "object",
                    "required": [],
                    "properties": {}
                },
                "depends_on": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "description": "IDs of the dependencies of this task"
                    }
                },
                "nfrs": {
                    "type": "object",
                    "required": [],
                    "properties": {}
                },
                "network_usage": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "required": [],
                    "properties": {}
                },
                "memory_consumption": {
                    "type": "number"
                },
                "runtime": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "disk_space_usage": {
                    "type": "string"
                },
                "energy_consumption": {
                    "type": "number"
                },
                "core_count": {
                    "type": "number"
                },
                "compute_granularity": {
                    "type": "string"
                },
                "compute_count": {
                    "type": "number"
                }
            }
        },
        "workflow": {
            "type": "object",
            "required": [],
            "properties": {
                "total_cpu": {
                    "type": "number",
                    "description": "Total CPU usage as a number in [0, 1]"
                },
                "domain": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/task"
                    }
                },
                "total_network_usage": {
                    "type": "string"
                },
                "critical_path_length": {
                    "type": "number"
                },
                "ts_submit": {
                    "type": "string"
                },
                "critical_path_task_count": {
                    "type": "number"
                },
                "approx_max_concurrent_tasks": {
                    "type": "number"
                },
                "task_count": {
                    "type": "number"
                },
                "scheduler": {
                    "type": "string"
                },
                "application_name": {
                    "type": "string"
                },
                "total_energy_consumption": {
                    "type": "string"
                },
                "total_memory_usage": {
                    "type": "string"
                },
                "total_disk_space_usage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "application_field": {
                    "type": "string"
                },
                "nfrs": {
                    "type": "object",
                    "required": [],
                    "properties": {}
                }
            }
        }
    }
}

=== atlarge-research/jsspp-osp/examples/workload.json
{
    "name": "Hello World Workload",
    "description": "An example workload",
    "domain": "bio-informatics",
    "authors": [
        "John Doe"
    ],
    "date_start": "2018-12-11T01:02:03",
    "date_end": "2018-12-11T02:03:04",
    "workflows": [
        {
            "id": "workflow-1",
            "total_cpu": 0.8,
            "total_network_usage": "10MB",
            "total_energy_usage": "100W",
            "total_memory_usage": "200MB",
            "total_disk_space_usage": "500MB",
            "ts_submit": "2018-12-11T01:02:03",
            "task_count": 2,
            "critical_path_task_count": 2,
            "approx_max_concurrent_tasks": 1,
            "tasks": [
                {
                    "id": "task-1",
                    "ts_submit": "2018-12-11T01:02:03",
                    "network_usage": "4MB",
                    "energy_usage": "90W",
                    "memory_usage": "200MB",
                    "disk_space_usage": "100MB",
                    "resources_used": [
                        {
                            "id": "machine-1",
                            "ncpu": 4,
                            "os": "Linux Debian 9.6",
                            "time_assigned": "2018-12-11T01:02:05",
                            "time_released": "2018-12-11T01:50:48",
                            "disk_space": "256GB"
                        }
                    ]
                },
                {
                    "id": "task-2",
                    "ts_submit": "2018-12-11T01:02:03",
                    "depends_on": [
                        "task-1"
                    ],
                    "network_usage": "6MB",
                    "energy_usage": "10W",
                    "memory_usage": "200MB",
                    "disk_space_usage": "400MB",
                    "data_transfers": [
                        {
                            "id": "transfer-1",
                            "size_unit": "MB",
                            "size": 100,
                            "transfer_time": "55s",
                            "ts_submit": "2018-12-11T02:00:22"
                        }
                    ],
                    "resources_used": [
                        {
                            "id": "machine-1",
                            "ncpu": 4,
                            "os": "Linux Debian 9.6",
                            "time_assigned": "2018-12-11T01:51:01",
                            "time_released": "2018-12-11T02:03:00",
                            "disk_space": "256GB"
                        }
                    ]
                }
            ]
        }
    ]
}
